#include "LPC407x_8x_177x_8x.h"

uint32_t ROBOT_SPEED = 70;
uint32_t ROTATION_NUMBER_FOR_90_DEGREE = 100;

uint8_t TURN_LEFT_FLAG;
uint8_t TURN_RIGHT_FLAG;
uint8_t FORWARD_FLAG;
uint8_t BACKWARD_FLAG;

uint8_t PRINT_AUTO=0;
uint8_t PRINT_MANUEL=0;

uint8_t OBSTACLE_DISTANCE = 15;
uint8_t OBSTACLE_ESCAPE_DISTANCE = 30;
uint8_t START_MODE=1;

